version: '2'
services:
  db:
    image: postgres:15
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo16@2022
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "odoo"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - odoo-network

  odoo16:
    image: odoo:16
    user: root
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "10016:8069"
      - "20016:8072" # live chat
    tty: true
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo16@2022
      - ODOO_CONF=/etc/odoo/odoo.conf
    volumes:
      - ./addons:/mnt/extra-addons
      - ./update_module_list.py:/scripts/update_module_list.py
      - ./etc:/etc/odoo
    entrypoint: >
      bash -c "
      python3 /scripts/update_module_list.py &&
      /entrypoint.sh odoo"
    restart: always
    networks:
      - odoo-network

networks:
  odoo-network:
    driver: bridge
