version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo16@2022
      POSTGRES_DB: odoo16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - odoo-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

  odoo16:
    image: myodoo:16
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "10016:8069" # Main Odoo service
      - "20016:8072" # Odoo longpolling service
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: odoo
      DB_PASSWORD: odoo16@2022
      DB_NAME: odoo16
      ODOO_CONF: /etc/odoo/odoo.conf
    volumes:
      - ./addons:/mnt/extra-addons
      - ./update_module_list.py:/scripts/update_module_list.py
      - ./etc:/etc/odoo
      - ./scripts:/scripts
      - ./logs:/var/log/odoo # Added logs directory for debugging
    entrypoint: >
      bash -c "
      sleep 10 &&
      /scripts/wait-for-it.sh db:5432 --timeout=60 &&
      /entrypoint.sh odoo -d odoo16 -i base --stop-after-init &&
      /entrypoint.sh odoo"
    networks:
      - odoo-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"

volumes:
  postgres_data: {}

networks:
  odoo-network:
    driver: bridge
